<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Admin.aspx.cs" Inherits="pm_web.Admin" %>
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>B M K </title>

    <!-- Bootstrap Core CSS -->
    <%-- <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">--%>
    <link href="bootstrap.min.css" rel="stylesheet" />

    <!-- Custom Fonts -->
    <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <%-- <link href="vendor/magnific-popup/magnific-popup.css" rel="stylesheet">--%>
    <link href="magnific-popup.css" rel="stylesheet" />

    <!-- Theme CSS -->
    <%-- <link href="css/creative.min.css" rel="stylesheet">--%>
    <link href="creative.min.css" rel="stylesheet" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
 <link href="StyleSheet1.css" rel="stylesheet" />
   
   
</head>

<body id="page-top">

    <form id="form1" runat="server">

    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">B M K</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="page-scroll" href="#services">mange </a>
                    </li>
                   <%-- <li>
                        <a class="page-scroll" href="#services">manager</a>
                    </li>--%>
                   <%-- <li>
                        <a class="page-scroll" href="#middel manger"> manger</a>
                    </li>--%>
                    <li>
                        <a class="page-scroll" href="#functional manger">middel manger & functional manger</a>

                    </li>
                    <li><a href="../general/WebForm1.aspx">Logout</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <header>
        <div class="header-content">
            <div class="header-content-inner">
                <h1 id="homeHeading">Your Favorite Source of Free Bootstrap Themes</h1>
                <hr/>
                <p>BMK</p>
                       <%--<div class="col-lg-8 col-lg-offset-2 text-center" >--%>
                    <div style=" width: 950px; height: 566px; margin-right:0px" >
                       <br />
                       <%--<div style="position:absolute;left:367px; top: -806px; height: 214px; width: 263px; "> --%>
                      
                      <%-- <h2 class="section-heading">--%>
                        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:pmConnectionString1 %>" SelectCommand="select *from register" UpdateCommand="update register set name=@name, phone=@phone,email=@email,[certificate]=@certificate,expeirence_years=@expeirence_years,manager_type=@manager_type where id=@id" DeleteCommand="delete from register where id=@id"></asp:SqlDataSource>
                      <%--  </h2>--%>
                    <hr class="light">
                    </div>
<asp:GridView ID="GridView1" runat="server"  AutoGenerateDeleteButton="True" BackColor="White" BorderColor="#CCCCCC" BorderWidth="1px" CellPadding="3" Width="708px" AllowPaging="True" AllowSorting="True" DataKeyNames="id" DataSourceID="SqlDataSource1" Height="16px" AllowCustomPaging="True" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" PageSize="5">
    <Columns>
        <asp:TemplateField HeaderText="add ">
            <ItemTemplate>
                <asp:Button ID="Button1" runat="server" CausesValidation="false" CommandName="Select" Text="Add" />
            </ItemTemplate>
        </asp:TemplateField>
    </Columns>
    <FooterStyle BackColor="White" ForeColor="#000066" />
    <HeaderStyle BackColor="#006699" Font-Bold="True" ForeColor="White" BorderWidth="5px" />
    <PagerStyle BackColor="White" ForeColor="#000066" HorizontalAlign="Left" />
    <RowStyle ForeColor="#000066" />
    <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
    <SortedAscendingCellStyle BackColor="#F1F1F1" BorderWidth="10px" />
    <SortedAscendingHeaderStyle BackColor="#007DBB" Width="7px" />
    <SortedDescendingCellStyle BackColor="#CAC9C9" />
    <SortedDescendingHeaderStyle BackColor="#00547E" />
                    </asp:GridView>
                       <br />
                      
                      
                       <asp:TextBox ID="TextBox1" CssClass="text"  placeholder="Add Username" runat="server" ForeColor="Black" Visible="False" OnTextChanged="TextBox1_TextChanged" ></asp:TextBox>
                           <br />
                           <br />
                           <asp:DropDownList ID="DropDownList1"  runat="server" ForeColor="Black" Height="33px" Visible="False" Width="148px" Font-Names="SketchFlow Print" OnSelectedIndexChanged="DropDownList1_SelectedIndexChanged">
                               <asp:ListItem Value="-1">select type</asp:ListItem>
                               <asp:ListItem Value="1">admin</asp:ListItem>
                               <asp:ListItem Value="2">pm manamger</asp:ListItem>
                               <asp:ListItem Value="3">middle</asp:ListItem>
                               <asp:ListItem Value="4">functional</asp:ListItem>
                           </asp:DropDownList>
                           <br />
                           <br />
                           <asp:TextBox ID="Textpas"  placeholder="Password"  runat="server" Visible="False" ForeColor="Black" ReadOnly="True"></asp:TextBox>
<br />
                           <br />
                           <asp:Button ID="Button2" runat="server" Text="Add account" Font-Names="SF Comic Script" ForeColor="Black" Visible="False" OnClick="Button2_Click" /> 
                           &nbsp;&nbsp;
                            <asp:Button ID="Button3" runat="server" Font-Names="Broadway" ForeColor="Black" Height="26px" Text="Send Email" Width="105px" OnClick="Button3_Click" Visible="False" />
                            <br />
                             
                        <asp:Label ID="Label1" runat="server" Text="Label" Font-Names="Ravie" ForeColor="#33CC33" Visible="False"></asp:Label>
                             
                             <br />
<asp:TextBox ID="TextBox2" runat="server" ForeColor="#FF6600" TextMode="MultiLine" Visible="False" OnTextChanged="TextBox2_TextChanged"></asp:TextBox>
            </div>
                            <br />
                            <br />
                      
                       <br />
                          <br />
                        <br />
                       <br />
                       <br />
                        <br />
                         <br />
                        <br />
                       <br />
            </div>
      
    </header>
        
        <br />
        <br />

 
          
  <section id="services" class="bg-light-gray">
      <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
               <asp:SqlDataSource ID="SqlDataSource6" runat="server" ConnectionString="<%$ ConnectionStrings:pmConnectionString1 %>" SelectCommand="SELECT * FROM middle" DeleteCommand="delete from middle where id=@id"></asp:SqlDataSource>
              <h2 class="section-heading">PM infromation<asp:SqlDataSource ID="SqlDataSource7" runat="server" ConnectionString="<%$ ConnectionStrings:pmConnectionString1 %>" SelectCommand="SELECT * FROM [manager]"  DeleteCommand="delete from [manager] where id=@id " UpdateCommand="update [manager] set name=@name,report=@report,image_pm=@image_pm,[The ratio]=@The ratio,titel=@titel where id=@id "></asp:SqlDataSource>
                    </h2>
                    <div style="margin-left:200px">
<asp:GridView ID="GridView7" runat="server" Width="644px" AllowPaging="True" AutoGenerateColumns="False" DataKeyNames="id" DataSourceID="SqlDataSource7" style="margin-right: 0px" CellPadding="4" ForeColor="#333333" GridLines="None">
                            <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
     <Columns>
         <asp:CommandField ShowDeleteButton="True" ShowEditButton="True" />
         <asp:BoundField DataField="id" HeaderText="ID" InsertVisible="False" ReadOnly="True" SortExpression="id" >
         <ControlStyle Width="0px" />
         <HeaderStyle HorizontalAlign="Center" Width="50px" />
         </asp:BoundField>
         <asp:BoundField DataField="name" HeaderText="  Name" SortExpression="name" >
         <HeaderStyle HorizontalAlign="Center" Width="70px" />
         </asp:BoundField>
         <asp:BoundField DataField="report" HeaderText="Report" SortExpression="report" Visible="False" >
         <HeaderStyle HorizontalAlign="Center" Width="65px" />
         </asp:BoundField>
         <asp:BoundField DataField="image_pm" HeaderText="Image Url" SortExpression="image_pm" >
         <HeaderStyle HorizontalAlign="Center" Width="90px" />
         </asp:BoundField>
         <asp:BoundField DataField="Order" HeaderText="Order" SortExpression="Order" Visible="False" />
         <asp:BoundField DataField="The ratio" HeaderText="The Ratio" SortExpression="The ratio" >
         <HeaderStyle HorizontalAlign="Center" Width="100px" />
         </asp:BoundField>
         <asp:BoundField DataField="titel" HeaderText="Titel" SortExpression="titel" >
         <HeaderStyle HorizontalAlign="Center" Width="80px" />
         </asp:BoundField>
     </Columns>
                            <EditRowStyle BackColor="#999999" />
                            <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                            <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                            <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                            <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                            <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                            <SortedAscendingCellStyle BackColor="#E9E7E2" />
                            <SortedAscendingHeaderStyle BackColor="#506C8C" />
                            <SortedDescendingCellStyle BackColor="#FFFDF8" />
                            <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
                    </asp:GridView>
                </div>

            </div>
                 </div>
        </div>
   </section>

    <section id="functional manger">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center"> <div style="margin-left:15%">
                    <asp:SqlDataSource ID="SqlDataSource3" runat="server" ConnectionString="<%$ ConnectionStrings:pmConnectionString1 %>" SelectCommand="SELECT * FROM [middle]" DeleteCommand="delete from [middle] where id=@id"></asp:SqlDataSource>
                    <br />
                   <h2 style="margin-left:-220px">middel infromation</h2>
                    <asp:GridView ID="GridView3" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" DataKeyNames="id" DataSourceID="SqlDataSource3" Height="177px" Width="591px" PageSize="5">
                        <Columns>
                            <asp:CommandField ShowDeleteButton="True" />
                            <asp:BoundField DataField="id" HeaderText="ID" InsertVisible="False" ReadOnly="True" SortExpression="id" />
                            <asp:BoundField DataField="name" HeaderText="Name" SortExpression="name" />
                            <asp:BoundField DataField="report" HeaderText="report" SortExpression="report" Visible="False" />
                        </Columns>
                    </asp:GridView></div>
                    <br />
                    <br />
                     <h2>Functional infromation</h2><asp:SqlDataSource ID="SqlDataSource8" runat="server" ConnectionString="<%$ ConnectionStrings:pmConnectionString1 %>" SelectCommand="SELECT * FROM [functional]" DeleteCommand="delete from [functional] where id=@id "></asp:SqlDataSource>
                       <div style="margin-left:200px"> <asp:GridView ID="GridView8" runat="server" AutoGenerateColumns="False" BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" CellPadding="3" DataKeyNames="id" DataSourceID="SqlDataSource8" ForeColor="Black" GridLines="Vertical" Height="193px" Width="381px" PageSize="5" AllowPaging="True">
                             <AlternatingRowStyle BackColor="#CCCCCC" />
                             <Columns>
                                 <asp:CommandField ShowDeleteButton="True" />
                                 <asp:BoundField DataField="id" HeaderText="ID" InsertVisible="False" ReadOnly="True" SortExpression="id" />
                                 <asp:BoundField DataField="report" HeaderText="report" SortExpression="report" Visible="False" />
                                 <asp:BoundField DataField="name" HeaderText="Name" SortExpression="name">
                                 <HeaderStyle Width="100px" />
                                 <ItemStyle ForeColor="#FF6600" />
                                 </asp:BoundField>
                             </Columns>
                             <FooterStyle BackColor="#CCCCCC" />
                             <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                             <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
                             <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                             <SortedAscendingCellStyle BackColor="#F1F1F1" />
                             <SortedAscendingHeaderStyle BackColor="#808080" />
                             <SortedDescendingCellStyle BackColor="#CAC9C9" />
                             <SortedDescendingHeaderStyle BackColor="#383838" />
                         </asp:GridView>

                       </div> 
                
                    <h2>
                         &nbsp;</h2>
                    <p>Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!</p>
                </div>
                <div class="col-lg-4 col-lg-offset-2 text-center">
                    <i class="fa fa-phone fa-3x sr-contact"></i>
                </div>
              
            </div>
        </div>
    </section>
       
  <div style="bottom:10px;">
                    <i class="fa fa-envelope-o fa-3x sr-contact"></i>
                    <p><a href="https://www.facebook.com/BMK.User/" style="margin-left:-280px">B M K</a></p>
                </div>
        <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <span class="copyright">B M K &copy; Your Website 2016</span>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline social-buttons">
                      <%--  <li><a href="#"><i class="fa fa-twitter"></i></a>
                        </li>--%>
                        <li><a href="https://www.facebook.com/BMK.User/"><i class="fa fa-facebook"></i></a>
                        </li>
                       <%-- <li><a href="#"><i class="fa fa-linkedin"></i></a>
                        </li>--%>
                    </ul>
                </div>
                <div class="col-md-4">
                    <%--<ul class="list-inline quicklinks">
                        <li><a href="#">Privacy Policy</a>
                        </li>
                        <li><a href="#">Terms of Use</a>
                        </li>
                    </ul>--%>
                </div>
            </div>
        </div>
    </footer>

    <!-- Portfolio Modals -->
    <!-- Use the modals below to showcase details about your portfolio projects! -->

    <!-- Portfolio Modal 1 -->
    <div class="portfolio-modal modal fade" id="portfolioModal1" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="close-modal" data-dismiss="modal">
                    <div class="lr">
                        <div class="rl">
                        </div>
                    </div>
                </div>
                <div class="container">
                    <div class="row">
                        <div class="col-lg-8 col-lg-offset-2">
                            <div class="modal-body">
                                <!-- Project Details Go Here -->
                                <h2>Project Name</h2>
                                <p class="item-intro text-muted">Lorem ipsum dolor sit amet consectetur.</p>
                                <img class="img-responsive img-centered" src="img/portfolio/roundicons-free.png" alt="">
                                <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>
                                <p>
                                    <strong>Want these icons in this portfolio item sample?</strong>You can download 60 of them for free, courtesy of <a href="https://getdpd.com/cart/hoplink/18076?referrer=bvbo4kax5k8ogc">RoundIcons.com</a>, or you can purchase the 1500 icon set <a href="https://getdpd.com/cart/hoplink/18076?referrer=bvbo4kax5k8ogc">here</a>.</p>
                                <ul class="list-inline">
                                    <li>Date: July 2014</li>
                                    <li>Client: Round Icons</li>
                                    <li>Category: Graphic Design</li>
                                </ul>
                                <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Close Project</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Portfolio Modal 2 -->
    <div class="portfolio-modal modal fade" id="portfolioModal2" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="close-modal" data-dismiss="modal">
                    <div class="lr">
                        <div class="rl">
                        </div>
                    </div>
                </div>
                <div class="container">
                    <div class="row">
                        <div class="col-lg-8 col-lg-offset-2">
                            <div class="modal-body">
                                <h2>Project Heading</h2>
                                <p class="item-intro text-muted">Lorem ipsum dolor sit amet consectetur.</p>
                                <img class="img-responsive img-centered" src="img/portfolio/startup-framework-preview.png" alt="">
                                <p><a href="http://designmodo.com/startup/?u=787">Startup Framework</a> is a website builder for professionals. Startup Framework contains components and complex blocks (PSD+HTML Bootstrap themes and templates) which can easily be integrated into almost any design. All of these components are made in the same style, and can easily be integrated into projects, allowing you to create hundreds of solutions for your future projects.</p>
                                <p>You can preview Startup Framework <a href="http://designmodo.com/startup/?u=787">here</a>.</p>
                                <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Close Project</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Portfolio Modal 3 -->
    <div class="portfolio-modal modal fade" id="portfolioModal3" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="close-modal" data-dismiss="modal">
                    <div class="lr">
                        <div class="rl">
                        </div>
                    </div>
                </div>
                <div class="container">
                    <div class="row">
                        <div class="col-lg-8 col-lg-offset-2">
                            <div class="modal-body">
                                <!-- Project Details Go Here -->
                                <h2>Project Name</h2>
                                <p class="item-intro text-muted">Lorem ipsum dolor sit amet consectetur.</p>
                                <img class="img-responsive img-centered" src="img/portfolio/treehouse-preview.png" alt="">
                                <p>Treehouse is a free PSD web template built by <a href="https://www.behance.net/MathavanJaya">Mathavan Jaya</a>. This is bright and spacious design perfect for people or startup companies looking to showcase their apps or other projects.</p>
                                <p>You can download the PSD template in this portfolio sample item at <a href="http://freebiesxpress.com/gallery/treehouse-free-psd-web-template/">FreebiesXpress.com</a>.</p>
                                <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Close Project</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Portfolio Modal 4 -->
    <div class="portfolio-modal modal fade" id="portfolioModal4" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="close-modal" data-dismiss="modal">
                    <div class="lr">
                        <div class="rl">
                        </div>
                    </div>
                </div>
                <div class="container">
                    <div class="row">
                        <div class="col-lg-8 col-lg-offset-2">
                            <div class="modal-body">
                                <!-- Project Details Go Here -->
                                <h2>Project Name</h2>
                                <p class="item-intro text-muted">Lorem ipsum dolor sit amet consectetur.</p>
                                <img class="img-responsive img-centered" src="img/portfolio/golden-preview.png" alt="">
                                <p>Start Bootstrap's Agency theme is based on Golden, a free PSD website template built by <a href="https://www.behance.net/MathavanJaya">Mathavan Jaya</a>. Golden is a modern and clean one page web template that was made exclusively for Best PSD Freebies. This template has a great portfolio, timeline, and meet your team sections that can be easily modified to fit your needs.</p>
                                <p>You can download the PSD template in this portfolio sample item at <a href="http://freebiesxpress.com/gallery/golden-free-one-page-web-template/">FreebiesXpress.com</a>.</p>
                                <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Close Project</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Portfolio Modal 5 -->
    <div class="portfolio-modal modal fade" id="portfolioModal5" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="close-modal" data-dismiss="modal">
                    <div class="lr">
                        <div class="rl">
                        </div>
                    </div>
                </div>
                <div class="container">
                    <div class="row">
                        <div class="col-lg-8 col-lg-offset-2">
                            <div class="modal-body">
                                <!-- Project Details Go Here -->
                                <h2>Project Name</h2>
                                <p class="item-intro text-muted">Lorem ipsum dolor sit amet consectetur.</p>
                                <img class="img-responsive img-centered" src="img/portfolio/escape-preview.png" alt="">
                                <p>Escape is a free PSD web template built by <a href="https://www.behance.net/MathavanJaya">Mathavan Jaya</a>. Escape is a one page web template that was designed with agencies in mind. This template is ideal for those looking for a simple one page solution to describe your business and offer your services.</p>
                                <p>You can download the PSD template in this portfolio sample item at <a href="http://freebiesxpress.com/gallery/escape-one-page-psd-web-template/">FreebiesXpress.com</a>.</p>
                                <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Close Project</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Portfolio Modal 6 -->
    <div class="portfolio-modal modal fade" id="portfolioModal6" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="close-modal" data-dismiss="modal">
                    <div class="lr">
                        <div class="rl">
                        </div>
                    </div>
                </div>
                <div class="container">
                    <div class="row">
                        <div class="col-lg-8 col-lg-offset-2">
                            <div class="modal-body">
                                <!-- Project Details Go Here -->
                                <h2>Project Name</h2>
                                <p class="item-intro text-muted">Lorem ipsum dolor sit amet consectetur.</p>
                                <img class="img-responsive img-centered" src="img/portfolio/dreams-preview.png" alt="">
                                <p>Dreams is a free PSD web template built by <a href="https://www.behance.net/MathavanJaya">Mathavan Jaya</a>. Dreams is a modern one page web template designed for almost any purpose. It’s a beautiful template that’s designed with the Bootstrap framework in mind.</p>
                                <p>You can download the PSD template in this portfolio sample item at <a href="http://freebiesxpress.com/gallery/dreams-free-one-page-web-template/">FreebiesXpress.com</a>.</p>
                                <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Close Project</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- jQuery -->
        
        <script src="jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
      
        <script src="bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="vendor/scrollreveal/scrollreveal.min.js"></script>
    <script src="vendor/magnific-popup/jquery.magnific-popup.min.js"></script>

    <!-- Theme JavaScript -->
        <script src="creative.min.js"></script>
    </form>

</body>

</html>

